# Generated by Django 3.2.15 on 2022-10-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('gerado', 'Documento gerado'), ('submetido', 'Documento submetido')], max_length=100, verbose_name='Tipo do documento')),
                ('documento_gerado', models.JSONField(blank=True, null=True, verbose_name='Documento gerado')),
                ('documento_gerado_modelo', models.CharField(blank=True, choices=[('honorarios', 'Honorários')], max_length=100, null=True, verbose_name='Modelo do documento gerado')),
                ('documento_submetido', models.FileField(blank=True, null=True, upload_to='', verbose_name='Documento submetido')),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
            ],
        ),
    ]
