# Generated by Django 3.2.15 on 2022-10-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documento', '0001_initial'),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.processo'),
        ),
    ]
