# Generated by Django 3.2.15 on 2022-10-01 08:04

from django.db import migrations, models
import projeto_advocacia.processo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('1', 'Código penal'), ('2', 'Contravenções penais'), ('3', 'Código de processo penal'), ('4', 'Crimes do sistema nacional de armas'), ('5', 'Crimes do sistema nacional de políticas públicas sobre Drogas'), ('6', 'Código de Trânsito Brasileiro'), ('7', 'Abuso de Autoridade'), ('8', 'Lavagem de dinheiro')], max_length=200, verbose_name='Categoria')),
                ('artigo', models.CharField(max_length=10, verbose_name='Artigo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pena_base', models.CharField(max_length=255, verbose_name='Pena base')),
                ('pena_fianca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fiança')),
                ('pena_agravante', models.TextField(blank=True, null=True, verbose_name='Agravante')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do serviço prestado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(default=projeto_advocacia.processo.models.gerar_numero_processo, max_length=20, verbose_name='Número do processo')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('fase', models.CharField(choices=[('postulatoria', 'Postulatória'), ('instrutoria', 'Instrutória'), ('decisoria', 'Decisória'), ('recursal', 'Recursal'), ('executiva', 'Executiva')], max_length=100, verbose_name='Fase')),
                ('tipo', models.CharField(choices=[('conhecimento', 'Conhecimento'), ('cautelar', 'Cautelar'), ('execução', 'Execução')], max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do processo')),
                ('postulatoria', models.TextField(blank=True, null=True, verbose_name='Descrição da fase Postulatória')),
                ('instrutoria', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Instrutória')),
                ('decisoria', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Decisória')),
                ('recursal', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Recursal')),
                ('executiva', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Executiva')),
            ],
        ),
    ]
