# Generated by Django 3.2.15 on 2022-09-27 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_auto_20220927_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Código penal'), ('2', 'Contravenções penais'), ('3', 'Código de processo penal'), ('4', 'Crimes do sistema nacional de armas'), ('5', 'Crimes do sistema nacional de políticas públicas sobre Drogas'), ('6', 'Código de Trânsito Brasileiro'), ('7', 'Abuso de Autoridade'), ('8', 'Lavagem de dinheiro')], max_length=200, verbose_name='Tipo')),
                ('artigo', models.CharField(max_length=10, verbose_name='Artigo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pena_base', models.CharField(max_length=255, verbose_name='Pena base')),
                ('pena_fianca', models.CharField(max_length=255, verbose_name='Fiança')),
                ('pena_agravante', models.TextField(verbose_name='Agravante')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(default='936521392', max_length=20)),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('fase', models.CharField(choices=[('1', 'Postulatória'), ('2', 'Instrutória'), ('3', 'Decisória'), ('4', 'Recursal'), ('5', 'Executiva')], max_length=50, verbose_name='Fase')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do processo')),
                ('postulatoria', models.TextField(blank=True, null=True, verbose_name='Descrição da fase Postulatória')),
                ('instrutória', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Instrutória')),
                ('decisória', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Decisória')),
                ('recursal', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Recursal')),
                ('executiva', models.TextField(blank=True, null=True, verbose_name='Descrição do fase Executiva')),
                ('advogado_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogado_autor', to=settings.AUTH_USER_MODEL)),
                ('advogado_reu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogado_reu', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='usuario.cliente')),
                ('juiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juiz', to=settings.AUTH_USER_MODEL)),
                ('reu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reu', to='usuario.cliente')),
            ],
        ),
    ]
