# Generated by Django 3.2.15 on 2022-10-01 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogado_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogado_autor', to=settings.AUTH_USER_MODEL, verbose_name='Advogado do autor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_reu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogado_reu', to=settings.AUTH_USER_MODEL, verbose_name='Advogado do Réu'),
        ),
        migrations.AddField(
            model_name='processo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='usuario.cliente', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juiz', to=settings.AUTH_USER_MODEL, verbose_name='Juiz'),
        ),
        migrations.AddField(
            model_name='processo',
            name='reu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reu', to='usuario.cliente', verbose_name='Réu'),
        ),
        migrations.AddField(
            model_name='prestacaoservico',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.cliente'),
        ),
        migrations.AddField(
            model_name='prestacaoservico',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resposável'),
        ),
        migrations.AddField(
            model_name='prestacaoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.servico', verbose_name='Serviço'),
        ),
    ]
