# Generated by Django 3.2.15 on 2022-10-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoservico',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processo.processo'),
        ),
        migrations.CreateModel(
            name='ServicoLeis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.lei')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.prestacaoservico')),
            ],
        ),
    ]
