# Generated by Django 3.2.15 on 2022-10-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_auto_20221003_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='artigo',
            field=models.CharField(max_length=200, verbose_name='Artigo'),
        ),
    ]
