# Generated by Django 3.2.15 on 2022-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_alter_processo_numero_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('1', 'Conhecimento'), ('2', 'Cautelar'), ('3', 'Execução')], default=1, max_length=50, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='671113487', max_length=20),
        ),
    ]
