# Generated by Django 3.2.15 on 2022-10-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_alter_lei_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='pena_fianca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Fiança'),
        ),
    ]
