# Generated by Django 3.2.15 on 2022-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_auto_20220927_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('postulatorio', 'Postulatória'), ('instrutoria', 'Instrutória'), ('decisoria', 'Decisória'), ('recursal', 'Recursal'), ('executiva', 'Executiva')], max_length=100, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='651321792', max_length=20),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('conhecimento', 'Conhecimento'), ('cautelar', 'Cautelar'), ('execucao', 'Execução')], max_length=100, verbose_name='Tipo'),
        ),
    ]
