# Generated by Django 3.2.15 on 2022-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_alter_lei_pena_fianca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lei',
            name='pena_base',
        ),
        migrations.AddField(
            model_name='lei',
            name='pena_base_meses',
            field=models.IntegerField(default=1, verbose_name='Meses da pena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lei',
            name='pena_base_multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Multa de pena'),
        ),
    ]
