# Generated by Django 3.2.15 on 2022-09-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0006_auto_20220927_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('Postulatória', 'Postulatória'), ('Instrutória', 'Instrutória'), ('Decisória', 'Decisória'), ('Recursal', 'Recursal'), ('Executiva', 'Executiva')], max_length=100, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='653425392', max_length=20),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('Conhecimento', 'Conhecimento'), ('Cautelar', 'Cautelar'), ('Execução', 'Execução')], max_length=100, verbose_name='Tipo'),
        ),
    ]
