# Generated by Django 3.2.15 on 2022-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0006_auto_20221004_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='pena_base_meses',
            field=models.IntegerField(default=0, verbose_name='Meses da pena'),
        ),
        migrations.AlterField(
            model_name='lei',
            name='pena_base_multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Multa de pena'),
        ),
    ]
