# Generated by Django 3.2.15 on 2022-10-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0007_auto_20221004_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoservico',
            name='pena_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pena do cliente'),
        ),
    ]
