# Generated by Django 3.2.15 on 2022-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0007_auto_20220927_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='516737746', max_length=20),
        ),
    ]
