# Generated by Django 3.2.15 on 2022-10-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0008_prestacaoservico_pena_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
