# Generated by Django 3.2.15 on 2022-09-28 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0005_auto_20220928_0306'),
        ('processo', '0009_alter_processo_numero_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='provas_autor',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Provas do Autor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='provas_reu',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Provas do réu'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogado_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogado_autor', to=settings.AUTH_USER_MODEL, verbose_name='Advogado do autor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogado_reu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advogado_reu', to=settings.AUTH_USER_MODEL, verbose_name='Advogado do Réu'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='usuario.cliente', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='juiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juiz', to=settings.AUTH_USER_MODEL, verbose_name='Juiz'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='185596972', max_length=20, verbose_name='Número do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='reu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reu', to='usuario.cliente', verbose_name='Réu'),
        ),
    ]
