# Generated by Django 3.2.15 on 2022-10-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0009_alter_lei_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='pena_agravante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agravante'),
        ),
    ]
