# Generated by Django 3.2.15 on 2022-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0010_auto_20220928_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='decisória',
            new_name='decisoria',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='instrutória',
            new_name='instrutoria',
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='172294651', max_length=20, verbose_name='Número do processo'),
        ),
    ]
