# Generated by Django 3.2.15 on 2022-10-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0010_alter_lei_pena_agravante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaoservico',
            name='pena_cliente',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Pena do cliente'),
        ),
    ]
