# Generated by Django 3.2.15 on 2022-09-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0011_auto_20220928_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='445856334', max_length=20, verbose_name='Número do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='provas_autor',
            field=models.FileField(blank=True, null=True, upload_to='provas_autor', verbose_name='Provas do Autor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='provas_reu',
            field=models.FileField(blank=True, null=True, upload_to='provas_reu', verbose_name='Provas do réu'),
        ),
    ]
