# Generated by Django 3.2.15 on 2022-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0011_alter_prestacaoservico_pena_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
