# Generated by Django 3.2.15 on 2022-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0012_auto_20220929_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='pena_agravante',
            field=models.TextField(blank=True, null=True, verbose_name='Agravante'),
        ),
        migrations.AlterField(
            model_name='lei',
            name='pena_fianca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fiança'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('postulatoria', 'Postulatória'), ('instrutoria', 'Instrutória'), ('decisoria', 'Decisória'), ('recursal', 'Recursal'), ('executiva', 'Executiva')], max_length=100, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='675758613', max_length=20, verbose_name='Número do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('conhecimento', 'Conhecimento'), ('cautelar', 'Cautelar'), ('execução', 'Execução')], max_length=100, verbose_name='Tipo'),
        ),
    ]
