# Generated by Django 3.2.15 on 2022-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0012_alter_lei_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='categoria',
            field=models.CharField(choices=[('1', 'Código penal'), ('2', 'Contravenções penais'), ('3', 'Código de processo penal'), ('4', 'Crimes do sistema nacional de armas'), ('5', 'Crimes do sistema nacional de políticas públicas sobre Drogas'), ('6', 'Código de Trânsito Brasileiro'), ('7', 'Abuso de Autoridade'), ('8', 'Lavagem de dinheiro'), ('9', 'Parte Geral')], max_length=200, verbose_name='Categoria'),
        ),
    ]
