# Generated by Django 3.2.15 on 2022-10-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0016_alter_processo_numero_processo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='provas_autor',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='provas_reu',
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='543378548', max_length=20, verbose_name='Número do processo'),
        ),
    ]
