# Generated by Django 3.2.15 on 2022-10-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0017_auto_20221001_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='165655164', max_length=20, verbose_name='Número do processo'),
        ),
    ]
