# Generated by Django 3.2.15 on 2022-10-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0022_auto_20221001_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default='875835557', max_length=20, verbose_name='Número do processo'),
        ),
    ]
