# Generated by Django 3.2.15 on 2022-10-01 07:56

from django.db import migrations, models
import projeto_advocacia.processo.models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0023_alter_processo_numero_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(default=projeto_advocacia.processo.models.gerar_numero_processo, max_length=20, verbose_name='Número do processo'),
        ),
    ]
