# Generated by Django 3.2.15 on 2022-09-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=250, verbose_name='Sobrenome')),
                ('passaporte', models.CharField(blank=True, max_length=10, null=True, verbose_name='Passaporte')),
                ('celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('organizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organização')),
                ('porte', models.BooleanField(blank=True, null=True, verbose_name='Porte')),
                ('cnh', models.BooleanField(blank=True, null=True, verbose_name='CNH')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='oab',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='OAB'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('0', 'Cliente'), ('1', 'Membro'), ('2', 'Administrador')], default='0', max_length=20, verbose_name='Cargo'),
        ),
    ]
