# Generated by Django 3.2.15 on 2022-10-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnh',
            field=models.BooleanField(default=1, verbose_name='CNH'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='porte',
            field=models.BooleanField(default=1, verbose_name='Porte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='organizacao',
            field=models.CharField(choices=[('0', 'Policia Militar'), ('1', 'Polícia Civil'), ('2', 'Fórum'), ('3', 'Prefeitura')], default=1, max_length=100, verbose_name='Organização'),
            preserve_default=False,
        ),
    ]
