# Generated by Django 3.2.15 on 2022-09-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identidade',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identidade',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Identidade'),
        ),
    ]
