# Generated by Django 3.2.15 on 2022-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20220928_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='organizacao',
            field=models.CharField(blank=True, choices=[('0', 'Policia Militar'), ('1', 'Polícia Civil'), ('2', 'Fórum'), ('3', 'Prefeitura')], max_length=100, null=True, verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='oab',
            field=models.BooleanField(default=False, verbose_name='OAB'),
        ),
    ]
