# Generated by Django 3.2.15 on 2022-10-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20220930_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=15, max_digits=15, verbose_name='Valor do serviço')),
                ('cargo_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo resposável')),
            ],
        ),
    ]
