# Generated by Django 3.2.15 on 2022-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_servico_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='oab',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_juridico',
            field=models.BooleanField(default=False, verbose_name='É do Fórum'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('0', 'Cliente'), ('1', 'Membro'), ('2', 'Advogado'), ('3', 'Promotor'), ('4', 'Juiz'), ('5', 'Juiz-Diretor')], default='0', max_length=20, verbose_name='Cargo'),
        ),
    ]
