# Generated by Django 3.2.15 on 2022-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20221001_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='valor',
            new_name='valor_base',
        ),
        migrations.AddField(
            model_name='servico',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='É ativo'),
        ),
    ]
